version: "3"

services:
  # db:
  #   build:
  #     context: ./db
  #   ports:
  #     - "5432:5432"
  #   restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8080:80"
    # depends_on:
    #   - db
    restart: always
    environment:
      - MONGO_URI=${MONGO_URI}



  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
        - backend
    restart: always
