export default [
  {
    name: "Ethiopia1",
    locations: [
      {
        name: "Adigrat",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.2778",
        longitude: "39.4611",
        location_type: "conflict_zone",
        conflict_date: "0",
        population: "86100",
      },
      {
        name: "Axum",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.122015",
        longitude: "38.7305334",
        location_type: "conflict_zone",
        conflict_date: "2",
        population: "66818",
      },
      {
        name: "Dansha",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.5662655",
        longitude: "36.9730465",
        location_type: "conflict_zone",
        conflict_date: "4",
        population: "407560",
      },
      {
        name: "Humera",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.2652",
        longitude: "36.585",
        location_type: "conflict_zone",
        conflict_date: "5",
        population: "32600",
      },
      {
        name: "May_Cadera",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.0747",
        longitude: "36.5685",
        location_type: "conflict_zone",
        conflict_date: "7",
        population: "19300",
      },
      {
        name: "Sheraro",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.4",
        longitude: "37.9333",
        location_type: "conflict_zone",
        conflict_date: "9",
        population: "26893",
      },
      {
        name: "Maychew",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "12.7875",
        longitude: "39.5422",
        location_type: "conflict_zone",
        conflict_date: "11",
        population: "35067",
      },
      {
        name: "Mekele",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.5",
        longitude: "39.4667",
        location_type: "conflict_zone",
        conflict_date: "16",
        population: "500000",
      },
      {
        name: "Shire",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1014",
        longitude: "38.2828",
        location_type: "conflict_zone",
        conflict_date: "16",
        population: "74503",
      },
      {
        name: "Idaga_Hamus",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.18722",
        longitude: "39.56389",
        location_type: "conflict_zone",
        conflict_date: "18",
        population: "10000",
      },
      {
        name: "Wukro",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.786854",
        longitude: "39.602968",
        location_type: "conflict_zone",
        conflict_date: "21",
        population: "45214",
      },
      {
        name: "Hawzen",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.9797481",
        longitude: "39.4308798",
        location_type: "conflict_zone",
        conflict_date: "21",
        population: "134856",
      },
      {
        name: "Dinglet",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.90892",
        longitude: "39.51265",
        location_type: "conflict_zone",
        conflict_date: "27",
        population: "10000",
      },
      {
        name: "Adwa",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1646303",
        longitude: "38.895478",
        location_type: "conflict_zone",
        conflict_date: "29",
        population: "108872",
      },
      {
        name: "Dangur",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "11.79",
        longitude: "36.1952",
        location_type: "conflict_zone",
        conflict_date: "5",
        population: "48537",
      },
      {
        name: "Dibate",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "10.65",
        longitude: "36.2155",
        location_type: "conflict_zone",
        conflict_date: "11",
        population: "89087",
      },
      {
        name: "Bulen",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "10.5833",
        longitude: "35.9167",
        location_type: "conflict_zone",
        conflict_date: "23",
        population: "62228",
      },
      {
        name: "Genete_Mariam",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "11.0167",
        longitude: "36.1",
        location_type: "conflict_zone",
        conflict_date: "23",
        population: "276367",
      },
      {
        name: "Gilgel_Belles",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "11.1618",
        longitude: "36.344",
        location_type: "conflict_zone",
        conflict_date: "51",
        population: "10000",
      },
      {
        name: "Wembera",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "10.5667",
        longitude: "35.55",
        location_type: "conflict_zone",
        conflict_date: "64",
        population: "79084",
      },
      {
        name: "Gubba",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "11.2664729",
        longitude: "35.2916214",
        location_type: "conflict_zone",
        conflict_date: "69",
        population: "20567",
      },
      {
        name: "Nazret",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.55",
        longitude: "39.267",
        location_type: "conflict_zone",
        conflict_date: "4",
        population: "324000",
      },
      {
        name: "Negele",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "5.3328174",
        longitude: "39.5806628",
        location_type: "conflict_zone",
        conflict_date: "7",
        population: "56897",
      },
      {
        name: "Ambo",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.982104",
        longitude: "37.8554406",
        location_type: "conflict_zone",
        conflict_date: "21",
        population: "77735",
      },
      {
        name: "Dilla",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "6.4099614",
        longitude: "38.3102763",
        location_type: "conflict_zone",
        conflict_date: "26",
        population: "79892",
      },
      {
        name: "Gimbi",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.8062736",
        longitude: "37.7881935",
        location_type: "conflict_zone",
        conflict_date: "31",
        population: "94917",
      },
      {
        name: "Shambu",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "9.566466",
        longitude: "37.100363",
        location_type: "conflict_zone",
        conflict_date: "34",
        population: "24196",
      },
      {
        name: "Nedjo",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "9.5046429",
        longitude: "35.501912",
        location_type: "conflict_zone",
        conflict_date: "41",
        population: "174888",
      },
      {
        name: "Dambidollo",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.5333",
        longitude: "34.8",
        location_type: "conflict_zone",
        conflict_date: "55",
        population: "43300",
      },
      {
        name: "Shashamane",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "7.2",
        longitude: "38.6",
        location_type: "conflict_zone",
        conflict_date: "56",
        population: "162127",
      },
      {
        name: "Mieso",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "9.2351",
        longitude: "40.7548",
        location_type: "conflict_zone",
        conflict_date: "59",
        population: "174916",
      },
      {
        name: "Siero",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.3205",
        longitude: "39.2253",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Adi_Ramets",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.7519496",
        longitude: "37.3201834",
        location_type: "town",
        conflict_date: "0",
        population: "15000",
      },
      {
        name: "Adi_Goshu",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1642",
        longitude: "37.3081",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Alamata",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "12.415682",
        longitude: "39.558081",
        location_type: "town",
        conflict_date: "0",
        population: "95094",
      },
      {
        name: "Aba_Guna",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.9491",
        longitude: "38.1837",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Dedebit",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.0746",
        longitude: "37.7639",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Denbe_Khabela",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.298",
        longitude: "37.7147",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Adi_Harush",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.592",
        longitude: "38.1311",
        location_type: "town",
        conflict_date: "0",
        population: "32167",
      },
      {
        name: "Mai_Aini",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.6565",
        longitude: "38.1541",
        location_type: "town",
        conflict_date: "0",
        population: "21682",
      },
      {
        name: "Hitsats",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1063655",
        longitude: "37.9561525",
        location_type: "town",
        conflict_date: "0",
        population: "25248",
      },
      {
        name: "Shimelba",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1768",
        longitude: "37.7231",
        location_type: "town",
        conflict_date: "0",
        population: "8702",
      },
      {
        name: "Gerhu_Sirnay",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.4911",
        longitude: "39.1735",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Rama",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.4114",
        longitude: "38.7842",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Adebay",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.2024117",
        longitude: "36.7576796",
        location_type: "town",
        conflict_date: "0",
        population: "31653",
      },
      {
        name: "Fireselam",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1125",
        longitude: "36.9471",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Korem",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "12.507546",
        longitude: "39.522289",
        location_type: "town",
        conflict_date: "0",
        population: "30633",
      },
      {
        name: "Adiy_Addi",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.622985",
        longitude: "38.999479",
        location_type: "town",
        conflict_date: "0",
        population: "26759",
      },
      {
        name: "Mehoni",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "12.8022",
        longitude: "39.6457",
        location_type: "town",
        conflict_date: "0",
        population: "20700",
      },
      {
        name: "Inticho",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.2779207",
        longitude: "39.1506252",
        location_type: "town",
        conflict_date: "0",
        population: "19000",
      },
      {
        name: "Hagere_Selam",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.6489",
        longitude: "39.1724",
        location_type: "town",
        conflict_date: "0",
        population: "5169",
      },
      {
        name: "Freweyni",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.054186",
        longitude: "39.577254",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Atsbi",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.8721",
        longitude: "39.7381",
        location_type: "town",
        conflict_date: "0",
        population: "130575",
      },
      {
        name: "Bako",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "9.1217306",
        longitude: "37.065626",
        location_type: "town",
        conflict_date: "0",
        population: "164298",
      },
      {
        name: "Mojo",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.5869874",
        longitude: "39.125",
        location_type: "town",
        conflict_date: "0",
        population: "43500",
      },
      {
        name: "Asosa",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "10.0646352",
        longitude: "34.5437024",
        location_type: "town",
        conflict_date: "0",
        population: "151075",
      },
      {
        name: "Bambasi",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "9.7604225",
        longitude: "34.7298772",
        location_type: "town",
        conflict_date: "0",
        population: "68594",
      },
      {
        name: "Arema",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "13.36337",
        longitude: "37.01777",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Wereta",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "11.9503",
        longitude: "37.7101",
        location_type: "town",
        conflict_date: "0",
        population: "33200",
      },
      {
        name: "Shehibi",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "12.7807",
        longitude: "36.4046",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Almahal",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "11.5456",
        longitude: "35.157",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Woldia",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "11.8284",
        longitude: "39.5973",
        location_type: "town",
        conflict_date: "0",
        population: "72300",
      },
      {
        name: "Midre_Genet",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "13.6944786",
        longitude: "36.4734299",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Metema",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "12.9543849",
        longitude: "36.1550794",
        location_type: "town",
        conflict_date: "0",
        population: "144843",
      },
      {
        name: "Enjebara",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "10.95855",
        longitude: "36.934574",
        location_type: "town",
        conflict_date: "0",
        population: "35846",
      },
      {
        name: "Semera",
        region: "Afar",
        country: "Ethiopia",
        latitude: "11.7922",
        longitude: "41.0088",
        location_type: "town",
        conflict_date: "0",
        population: "100000",
      },
      {
        name: "Awash",
        region: "Afar",
        country: "Ethiopia",
        latitude: "8.992496",
        longitude: "40.167674",
        location_type: "town",
        conflict_date: "0",
        population: "46909",
      },
      {
        name: "Addis_Ababa",
        region: "Addis_Ababa",
        country: "Ethiopia",
        latitude: "9.0107934",
        longitude: "38.7612525",
        location_type: "town",
        conflict_date: "0",
        population: "4793699",
      },
      {
        name: "Bahir_Dar",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "11.6",
        longitude: "37.3833",
        location_type: "camp",
        conflict_date: "0",
        population: "750991",
      },
      {
        name: "Gondar",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "12.6",
        longitude: "37.4667",
        location_type: "camp",
        conflict_date: "0",
        population: "740859",
      },
      {
        name: "Hamdayet",
        region: "Kassala",
        country: "Sudan",
        latitude: "14.26856",
        longitude: "36.53171",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Lugdi",
        region: "Gedaref",
        country: "Sudan",
        latitude: "14.15507",
        longitude: "36.4792871",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Abderafi",
        region: "Gedaref",
        country: "Sudan",
        latitude: "13.7377",
        longitude: "36.4334",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Wad_Al_Mahi",
        region: "Blue_Nile",
        country: "Sudan",
        latitude: "11.416667",
        longitude: "34.616667",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Sehra",
        region: "Debub",
        country: "Eritrea",
        latitude: "14.5465",
        longitude: "39.3904",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Tsorona",
        region: "Debub",
        country: "Eritrea",
        latitude: "14.6231",
        longitude: "39.1972",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Galafi",
        region: "Dikhil",
        country: "Djibouti",
        latitude: "11.7169",
        longitude: "41.8375",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
    ],
    routes: [
      {
        from: "Alamata",
        to: "Woldia",
        distance: "80",
        forced_redirection: "",
      },
      {
        from: "Wereta",
        to: "Woldia",
        distance: "297",
        forced_redirection: "",
      },
      {
        from: "Woldia",
        to: "Semera",
        distance: "245",
        forced_redirection: "",
      },
      {
        from: "Semera",
        to: "Galafi",
        distance: "114",
        forced_redirection: "",
      },
      {
        from: "Alamata",
        to: "Mehoni",
        distance: "50",
        forced_redirection: "",
      },
      {
        from: "Alamata",
        to: "Korem",
        distance: "20",
        forced_redirection: "",
      },
      {
        from: "Korem",
        to: "Maychew",
        distance: "41",
        forced_redirection: "",
      },
      {
        from: "Maychew",
        to: "Mehoni",
        distance: "18",
        forced_redirection: "",
      },
      {
        from: "Maychew",
        to: "Mekele",
        distance: "129",
        forced_redirection: "",
      },
      {
        from: "Mekele",
        to: "Hagere_Selam",
        distance: "55",
        forced_redirection: "",
      },
      {
        from: "Hagere_Selam",
        to: "Adiy_Addi",
        distance: "43",
        forced_redirection: "",
      },
      {
        from: "Mekele",
        to: "Wukro",
        distance: "47",
        forced_redirection: "",
      },
      {
        from: "Wukro",
        to: "Adiy_Addi",
        distance: "114",
        forced_redirection: "",
      },
      {
        from: "Wukro",
        to: "Dinglet",
        distance: "25",
        forced_redirection: "",
      },
      {
        from: "Dinglet",
        to: "Freweyni",
        distance: "23",
        forced_redirection: "",
      },
      {
        from: "Wukro",
        to: "Atsbi",
        distance: "26",
        forced_redirection: "",
      },
      {
        from: "Freweyni",
        to: "Hawzen",
        distance: "22",
        forced_redirection: "",
      },
      {
        from: "Dinglet",
        to: "Hawzen",
        distance: "23",
        forced_redirection: "",
      },
      {
        from: "Adiy_Addi",
        to: "Hawzen",
        distance: "82",
        forced_redirection: "",
      },
      {
        from: "Freweyni",
        to: "Idaga_Hamus",
        distance: "17",
        forced_redirection: "",
      },
      {
        from: "Idaga_Hamus",
        to: "Adigrat",
        distance: "20",
        forced_redirection: "",
      },
      {
        from: "Adigrat",
        to: "Siero",
        distance: "51",
        forced_redirection: "",
      },
      {
        from: "Adigrat",
        to: "Sehra",
        distance: "41",
        forced_redirection: "",
      },
      {
        from: "Siero",
        to: "Gerhu_Sirnay",
        distance: "30",
        forced_redirection: "",
      },
      {
        from: "Gerhu_Sirnay",
        to: "Tsorona",
        distance: "21",
        forced_redirection: "",
      },
      {
        from: "Adwa",
        to: "Rama",
        distance: "38",
        forced_redirection: "",
      },
      {
        from: "Siero",
        to: "Inticho",
        distance: "16",
        forced_redirection: "",
      },
      {
        from: "Inticho",
        to: "Adwa",
        distance: "40",
        forced_redirection: "",
      },
      {
        from: "Adwa",
        to: "Axum",
        distance: "21",
        forced_redirection: "",
      },
      {
        from: "Axum",
        to: "Shire",
        distance: "64",
        forced_redirection: "",
      },
      {
        from: "Shire",
        to: "Sheraro",
        distance: "77",
        forced_redirection: "",
      },
      {
        from: "Shire",
        to: "Aba_Guna",
        distance: "21",
        forced_redirection: "",
      },
      {
        from: "Aba_Guna",
        to: "Mai_Aini",
        distance: "47",
        forced_redirection: "",
      },
      {
        from: "Mai_Aini",
        to: "Adi_Harush",
        distance: "11",
        forced_redirection: "",
      },
      {
        from: "Adi_Harush",
        to: "Gondar",
        distance: "207",
        forced_redirection: "",
      },
      {
        from: "Shire",
        to: "Hitsats",
        distance: "44",
        forced_redirection: "",
      },
      {
        from: "Hitsats",
        to: "Shimelba",
        distance: "50",
        forced_redirection: "",
      },
      {
        from: "Shimelba",
        to: "Denbe_Khabela",
        distance: "16",
        forced_redirection: "",
      },
      {
        from: "Sheraro",
        to: "Denbe_Khabela",
        distance: "31",
        forced_redirection: "",
      },
      {
        from: "Denbe_Khabela",
        to: "Adi_Goshu",
        distance: "66",
        forced_redirection: "",
      },
      {
        from: "Hitsats",
        to: "Dedebit",
        distance: "32",
        forced_redirection: "",
      },
      {
        from: "Dedebit",
        to: "Shimelba",
        distance: "14",
        forced_redirection: "",
      },
      {
        from: "Dedebit",
        to: "Adi_Goshu",
        distance: "87",
        forced_redirection: "",
      },
      {
        from: "Adi_Goshu",
        to: "Fireselam",
        distance: "50",
        forced_redirection: "",
      },
      {
        from: "Fireselam",
        to: "Adebay",
        distance: "23",
        forced_redirection: "",
      },
      {
        from: "Adebay",
        to: "Humera",
        distance: "19",
        forced_redirection: "",
      },
      {
        from: "Humera",
        to: "Hamdayet",
        distance: "20",
        forced_redirection: "",
      },
      {
        from: "Humera",
        to: "Adi_Ramets",
        distance: "125",
        forced_redirection: "",
      },
      {
        from: "Humera",
        to: "Dansha",
        distance: "102",
        forced_redirection: "",
      },
      {
        from: "Humera",
        to: "May_Cadera",
        distance: "30",
        forced_redirection: "",
      },
      {
        from: "May_Cadera",
        to: "Dansha",
        distance: "108",
        forced_redirection: "",
      },
      {
        from: "May_Cadera",
        to: "Adi_Ramets",
        distance: "126",
        forced_redirection: "",
      },
      {
        from: "May_Cadera",
        to: "Lugdi",
        distance: "14",
        forced_redirection: "",
      },
      {
        from: "May_Cadera",
        to: "Midre_Genet",
        distance: "47",
        forced_redirection: "",
      },
      {
        from: "Midre_Genet",
        to: "Abderafi",
        distance: "7",
        forced_redirection: "",
      },
      {
        from: "Midre_Genet",
        to: "Arema",
        distance: "108",
        forced_redirection: "",
      },
      {
        from: "Adi_Goshu",
        to: "Adi_Ramets",
        distance: "102",
        forced_redirection: "",
      },
      {
        from: "Adi_Ramets",
        to: "Gondar",
        distance: "189",
        forced_redirection: "",
      },
      {
        from: "Adi_Ramets",
        to: "Dansha",
        distance: "89",
        forced_redirection: "",
      },
      {
        from: "Dansha",
        to: "Arema",
        distance: "28",
        forced_redirection: "",
      },
      {
        from: "Arema",
        to: "Gondar",
        distance: "124",
        forced_redirection: "",
      },
      {
        from: "Gondar",
        to: "Dangur",
        distance: "61",
        forced_redirection: "",
      },
      {
        from: "Dangur",
        to: "Shehibi",
        distance: "106",
        forced_redirection: "",
      },
      {
        from: "Gondar",
        to: "Wereta",
        distance: "117",
        forced_redirection: "",
      },
      {
        from: "Wereta",
        to: "Bahir_Dar",
        distance: "61",
        forced_redirection: "",
      },
      {
        from: "Bahir_Dar",
        to: "Gilgel_Belles",
        distance: "172",
        forced_redirection: "",
      },
      {
        from: "Genete_Mariam",
        to: "Gilgel_Belles",
        distance: "70",
        forced_redirection: "",
      },
      {
        from: "Genete_Mariam",
        to: "Gubba",
        distance: "107",
        forced_redirection: "",
      },
      {
        from: "Shehibi",
        to: "Metema",
        distance: "35",
        forced_redirection: "",
      },
      {
        from: "Metema",
        to: "Midre_Genet",
        distance: "135",
        forced_redirection: "",
      },
      {
        from: "Shehibi",
        to: "Almahal",
        distance: "380",
        forced_redirection: "",
      },
      {
        from: "Almahal",
        to: "Wad_Al_Mahi",
        distance: "76",
        forced_redirection: "",
      },
      {
        from: "Almahal",
        to: "Gubba",
        distance: "51",
        forced_redirection: "",
      },
      {
        from: "Gubba",
        to: "Asosa",
        distance: "243",
        forced_redirection: "",
      },
      {
        from: "Asosa",
        to: "Bambasi",
        distance: "43",
        forced_redirection: "",
      },
      {
        from: "Bambasi",
        to: "Nedjo",
        distance: "122",
        forced_redirection: "",
      },
      {
        from: "Gilgel_Belles",
        to: "Dibate",
        distance: "77",
        forced_redirection: "",
      },
      {
        from: "Gubba",
        to: "Wembera",
        distance: "121",
        forced_redirection: "",
      },
      {
        from: "Wembera",
        to: "Bulen",
        distance: "80",
        forced_redirection: "",
      },
      {
        from: "Bulen",
        to: "Dibate",
        distance: "36",
        forced_redirection: "",
      },
      {
        from: "Bahir_Dar",
        to: "Enjebara",
        distance: "114",
        forced_redirection: "",
      },
      {
        from: "Enjebara",
        to: "Dibate",
        distance: "121",
        forced_redirection: "",
      },
      {
        from: "Enjebara",
        to: "Shambu",
        distance: "216",
        forced_redirection: "",
      },
      {
        from: "Shambu",
        to: "Bako",
        distance: "66",
        forced_redirection: "",
      },
      {
        from: "Bako",
        to: "Nedjo",
        distance: "261",
        forced_redirection: "",
      },
      {
        from: "Nedjo",
        to: "Dambidollo",
        distance: "198",
        forced_redirection: "",
      },
      {
        from: "Dambidollo",
        to: "Bambasi",
        distance: "224",
        forced_redirection: "",
      },
      {
        from: "Bako",
        to: "Ambo",
        distance: "121",
        forced_redirection: "",
      },
      {
        from: "Ambo",
        to: "Gimbi",
        distance: "29",
        forced_redirection: "",
      },
      {
        from: "Ambo",
        to: "Addis_Ababa",
        distance: "115",
        forced_redirection: "",
      },
      {
        from: "Bahir_Dar",
        to: "Addis_Ababa",
        distance: "486",
        forced_redirection: "",
      },
      {
        from: "Addis_Ababa",
        to: "Mojo",
        distance: "77",
        forced_redirection: "",
      },
      {
        from: "Mojo",
        to: "Nazret",
        distance: "20",
        forced_redirection: "",
      },
      {
        from: "Nazret",
        to: "Awash",
        distance: "123",
        forced_redirection: "",
      },
      {
        from: "Awash",
        to: "Mieso",
        distance: "79",
        forced_redirection: "",
      },
      {
        from: "Awash",
        to: "Galafi",
        distance: "488",
        forced_redirection: "",
      },
      {
        from: "Mojo",
        to: "Shashamane",
        distance: "178",
        forced_redirection: "",
      },
      {
        from: "Shashamane",
        to: "Dilla",
        distance: "110",
        forced_redirection: "",
      },
      {
        from: "Dilla",
        to: "Negele",
        distance: "260",
        forced_redirection: "",
      },
    ],
  },
  {
    name: "Other Ethiopia",
    locations: [
      {
        name: "Adigrat",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.2778",
        longitude: "39.4611",
        location_type: "conflict_zone",
        conflict_date: "0",
        population: "86100",
      },
      {
        name: "Axum",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.122015",
        longitude: "38.7305334",
        location_type: "conflict_zone",
        conflict_date: "2",
        population: "66818",
      },
      {
        name: "Dansha",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.5662655",
        longitude: "36.9730465",
        location_type: "conflict_zone",
        conflict_date: "4",
        population: "407560",
      },
      {
        name: "Humera",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.2652",
        longitude: "36.585",
        location_type: "conflict_zone",
        conflict_date: "5",
        population: "32600",
      },
      {
        name: "May_Cadera",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.0747",
        longitude: "36.5685",
        location_type: "conflict_zone",
        conflict_date: "7",
        population: "19300",
      },
      {
        name: "Sheraro",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.4",
        longitude: "37.9333",
        location_type: "conflict_zone",
        conflict_date: "9",
        population: "26893",
      },
      {
        name: "Maychew",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "12.7875",
        longitude: "39.5422",
        location_type: "conflict_zone",
        conflict_date: "11",
        population: "35067",
      },
      {
        name: "Mekele",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.5",
        longitude: "39.4667",
        location_type: "conflict_zone",
        conflict_date: "16",
        population: "500000",
      },
      {
        name: "Shire",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1014",
        longitude: "38.2828",
        location_type: "conflict_zone",
        conflict_date: "16",
        population: "74503",
      },
      {
        name: "Idaga_Hamus",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.18722",
        longitude: "39.56389",
        location_type: "conflict_zone",
        conflict_date: "18",
        population: "10000",
      },
      {
        name: "Wukro",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.786854",
        longitude: "39.602968",
        location_type: "conflict_zone",
        conflict_date: "21",
        population: "45214",
      },
      {
        name: "Hawzen",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.9797481",
        longitude: "39.4308798",
        location_type: "conflict_zone",
        conflict_date: "21",
        population: "134856",
      },
      {
        name: "Dinglet",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.90892",
        longitude: "39.51265",
        location_type: "conflict_zone",
        conflict_date: "27",
        population: "10000",
      },
      {
        name: "Adwa",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1646303",
        longitude: "38.895478",
        location_type: "conflict_zone",
        conflict_date: "29",
        population: "108872",
      },
      {
        name: "Dangur",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "11.79",
        longitude: "36.1952",
        location_type: "conflict_zone",
        conflict_date: "5",
        population: "48537",
      },
      {
        name: "Dibate",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "10.65",
        longitude: "36.2155",
        location_type: "conflict_zone",
        conflict_date: "11",
        population: "89087",
      },
      {
        name: "Bulen",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "10.5833",
        longitude: "35.9167",
        location_type: "conflict_zone",
        conflict_date: "23",
        population: "62228",
      },
      {
        name: "Genete_Mariam",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "11.0167",
        longitude: "36.1",
        location_type: "conflict_zone",
        conflict_date: "23",
        population: "276367",
      },
      {
        name: "Gilgel_Belles",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "11.1618",
        longitude: "36.344",
        location_type: "conflict_zone",
        conflict_date: "51",
        population: "10000",
      },
      {
        name: "Wembera",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "10.5667",
        longitude: "35.55",
        location_type: "conflict_zone",
        conflict_date: "64",
        population: "79084",
      },
      {
        name: "Gubba",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "11.2664729",
        longitude: "35.2916214",
        location_type: "conflict_zone",
        conflict_date: "69",
        population: "20567",
      },
      {
        name: "Nazret",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.55",
        longitude: "39.267",
        location_type: "conflict_zone",
        conflict_date: "4",
        population: "324000",
      },
      {
        name: "Negele",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "5.3328174",
        longitude: "39.5806628",
        location_type: "conflict_zone",
        conflict_date: "7",
        population: "56897",
      },
      {
        name: "Ambo",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.982104",
        longitude: "37.8554406",
        location_type: "conflict_zone",
        conflict_date: "21",
        population: "77735",
      },
      {
        name: "Dilla",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "6.4099614",
        longitude: "38.3102763",
        location_type: "conflict_zone",
        conflict_date: "26",
        population: "79892",
      },
      {
        name: "Gimbi",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.8062736",
        longitude: "37.7881935",
        location_type: "conflict_zone",
        conflict_date: "31",
        population: "94917",
      },
      {
        name: "Shambu",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "9.566466",
        longitude: "37.100363",
        location_type: "conflict_zone",
        conflict_date: "34",
        population: "24196",
      },
      {
        name: "Nedjo",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "9.5046429",
        longitude: "35.501912",
        location_type: "conflict_zone",
        conflict_date: "41",
        population: "174888",
      },
      {
        name: "Dambidollo",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.5333",
        longitude: "34.8",
        location_type: "conflict_zone",
        conflict_date: "55",
        population: "43300",
      },
      {
        name: "Shashamane",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "7.2",
        longitude: "38.6",
        location_type: "conflict_zone",
        conflict_date: "56",
        population: "162127",
      },
      {
        name: "Mieso",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "9.2351",
        longitude: "40.7548",
        location_type: "conflict_zone",
        conflict_date: "59",
        population: "174916",
      },
      {
        name: "Siero",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.3205",
        longitude: "39.2253",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Adi_Ramets",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.7519496",
        longitude: "37.3201834",
        location_type: "town",
        conflict_date: "0",
        population: "15000",
      },
      {
        name: "Adi_Goshu",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1642",
        longitude: "37.3081",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Alamata",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "12.415682",
        longitude: "39.558081",
        location_type: "town",
        conflict_date: "0",
        population: "95094",
      },
      {
        name: "Aba_Guna",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.9491",
        longitude: "38.1837",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Dedebit",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.0746",
        longitude: "37.7639",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Denbe_Khabela",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.298",
        longitude: "37.7147",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Adi_Harush",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.592",
        longitude: "38.1311",
        location_type: "town",
        conflict_date: "0",
        population: "32167",
      },
      {
        name: "Mai_Aini",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.6565",
        longitude: "38.1541",
        location_type: "town",
        conflict_date: "0",
        population: "21682",
      },
      {
        name: "Hitsats",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1063655",
        longitude: "37.9561525",
        location_type: "town",
        conflict_date: "0",
        population: "25248",
      },
      {
        name: "Shimelba",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1768",
        longitude: "37.7231",
        location_type: "town",
        conflict_date: "0",
        population: "8702",
      },
      {
        name: "Gerhu_Sirnay",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.4911",
        longitude: "39.1735",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Rama",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.4114",
        longitude: "38.7842",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Adebay",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.2024117",
        longitude: "36.7576796",
        location_type: "town",
        conflict_date: "0",
        population: "31653",
      },
      {
        name: "Fireselam",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.1125",
        longitude: "36.9471",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Korem",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "12.507546",
        longitude: "39.522289",
        location_type: "town",
        conflict_date: "0",
        population: "30633",
      },
      {
        name: "Adiy_Addi",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.622985",
        longitude: "38.999479",
        location_type: "town",
        conflict_date: "0",
        population: "26759",
      },
      {
        name: "Mehoni",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "12.8022",
        longitude: "39.6457",
        location_type: "town",
        conflict_date: "0",
        population: "20700",
      },
      {
        name: "Inticho",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.2779207",
        longitude: "39.1506252",
        location_type: "town",
        conflict_date: "0",
        population: "19000",
      },
      {
        name: "Hagere_Selam",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.6489",
        longitude: "39.1724",
        location_type: "town",
        conflict_date: "0",
        population: "5169",
      },
      {
        name: "Freweyni",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "14.054186",
        longitude: "39.577254",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Atsbi",
        region: "Tigray",
        country: "Ethiopia",
        latitude: "13.8721",
        longitude: "39.7381",
        location_type: "town",
        conflict_date: "0",
        population: "130575",
      },
      {
        name: "Bako",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "9.1217306",
        longitude: "37.065626",
        location_type: "town",
        conflict_date: "0",
        population: "164298",
      },
      {
        name: "Mojo",
        region: "Oromia",
        country: "Ethiopia",
        latitude: "8.5869874",
        longitude: "39.125",
        location_type: "town",
        conflict_date: "0",
        population: "43500",
      },
      {
        name: "Asosa",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "10.0646352",
        longitude: "34.5437024",
        location_type: "town",
        conflict_date: "0",
        population: "151075",
      },
      {
        name: "Bambasi",
        region: "Benshangul_Gumaz",
        country: "Ethiopia",
        latitude: "9.7604225",
        longitude: "34.7298772",
        location_type: "town",
        conflict_date: "0",
        population: "68594",
      },
      {
        name: "Arema",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "13.36337",
        longitude: "37.01777",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Wereta",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "11.9503",
        longitude: "37.7101",
        location_type: "town",
        conflict_date: "0",
        population: "33200",
      },
      {
        name: "Shehibi",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "12.7807",
        longitude: "36.4046",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Almahal",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "11.5456",
        longitude: "35.157",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Woldia",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "11.8284",
        longitude: "39.5973",
        location_type: "town",
        conflict_date: "0",
        population: "72300",
      },
      {
        name: "Midre_Genet",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "13.6944786",
        longitude: "36.4734299",
        location_type: "town",
        conflict_date: "0",
        population: "10000",
      },
      {
        name: "Metema",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "12.9543849",
        longitude: "36.1550794",
        location_type: "town",
        conflict_date: "0",
        population: "144843",
      },
      {
        name: "Enjebara",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "10.95855",
        longitude: "36.934574",
        location_type: "town",
        conflict_date: "0",
        population: "35846",
      },
      {
        name: "Semera",
        region: "Afar",
        country: "Ethiopia",
        latitude: "11.7922",
        longitude: "41.0088",
        location_type: "town",
        conflict_date: "0",
        population: "100000",
      },
      {
        name: "Awash",
        region: "Afar",
        country: "Ethiopia",
        latitude: "8.992496",
        longitude: "40.167674",
        location_type: "town",
        conflict_date: "0",
        population: "46909",
      },
      {
        name: "Addis_Ababa",
        region: "Addis_Ababa",
        country: "Ethiopia",
        latitude: "9.0107934",
        longitude: "38.7612525",
        location_type: "town",
        conflict_date: "0",
        population: "4793699",
      },
      {
        name: "Bahir_Dar",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "11.6",
        longitude: "37.3833",
        location_type: "camp",
        conflict_date: "0",
        population: "750991",
      },
      {
        name: "Gondar",
        region: "Amhara",
        country: "Ethiopia",
        latitude: "12.6",
        longitude: "37.4667",
        location_type: "camp",
        conflict_date: "0",
        population: "740859",
      },
      {
        name: "Hamdayet",
        region: "Kassala",
        country: "Sudan",
        latitude: "14.26856",
        longitude: "36.53171",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Lugdi",
        region: "Gedaref",
        country: "Sudan",
        latitude: "14.15507",
        longitude: "36.4792871",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Abderafi",
        region: "Gedaref",
        country: "Sudan",
        latitude: "13.7377",
        longitude: "36.4334",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Wad_Al_Mahi",
        region: "Blue_Nile",
        country: "Sudan",
        latitude: "11.416667",
        longitude: "34.616667",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Sehra",
        region: "Debub",
        country: "Eritrea",
        latitude: "14.5465",
        longitude: "39.3904",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Tsorona",
        region: "Debub",
        country: "Eritrea",
        latitude: "14.6231",
        longitude: "39.1972",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
      {
        name: "Galafi",
        region: "Dikhil",
        country: "Djibouti",
        latitude: "11.7169",
        longitude: "41.8375",
        location_type: "camp",
        conflict_date: "0",
        population: "1000000",
      },
    ],
    routes: [
      {
        from: "Alamata",
        to: "Woldia",
        distance: "80",
        forced_redirection: "",
      },
      {
        from: "Wereta",
        to: "Woldia",
        distance: "297",
        forced_redirection: "",
      },
      {
        from: "Woldia",
        to: "Semera",
        distance: "245",
        forced_redirection: "",
      },
      {
        from: "Semera",
        to: "Galafi",
        distance: "114",
        forced_redirection: "",
      },
      {
        from: "Alamata",
        to: "Mehoni",
        distance: "50",
        forced_redirection: "",
      },
      {
        from: "Alamata",
        to: "Korem",
        distance: "20",
        forced_redirection: "",
      },
      {
        from: "Korem",
        to: "Maychew",
        distance: "41",
        forced_redirection: "",
      },
      {
        from: "Maychew",
        to: "Mehoni",
        distance: "18",
        forced_redirection: "",
      },
      {
        from: "Maychew",
        to: "Mekele",
        distance: "129",
        forced_redirection: "",
      },
      {
        from: "Mekele",
        to: "Hagere_Selam",
        distance: "55",
        forced_redirection: "",
      },
      {
        from: "Hagere_Selam",
        to: "Adiy_Addi",
        distance: "43",
        forced_redirection: "",
      },
      {
        from: "Mekele",
        to: "Wukro",
        distance: "47",
        forced_redirection: "",
      },
      {
        from: "Wukro",
        to: "Adiy_Addi",
        distance: "114",
        forced_redirection: "",
      },
      {
        from: "Wukro",
        to: "Dinglet",
        distance: "25",
        forced_redirection: "",
      },
      {
        from: "Dinglet",
        to: "Freweyni",
        distance: "23",
        forced_redirection: "",
      },
      {
        from: "Wukro",
        to: "Atsbi",
        distance: "26",
        forced_redirection: "",
      },
      {
        from: "Freweyni",
        to: "Hawzen",
        distance: "22",
        forced_redirection: "",
      },
      {
        from: "Dinglet",
        to: "Hawzen",
        distance: "23",
        forced_redirection: "",
      },
      {
        from: "Adiy_Addi",
        to: "Hawzen",
        distance: "82",
        forced_redirection: "",
      },
      {
        from: "Freweyni",
        to: "Idaga_Hamus",
        distance: "17",
        forced_redirection: "",
      },
      {
        from: "Idaga_Hamus",
        to: "Adigrat",
        distance: "20",
        forced_redirection: "",
      },
      {
        from: "Adigrat",
        to: "Siero",
        distance: "51",
        forced_redirection: "",
      },
      {
        from: "Adigrat",
        to: "Sehra",
        distance: "41",
        forced_redirection: "",
      },
      {
        from: "Siero",
        to: "Gerhu_Sirnay",
        distance: "30",
        forced_redirection: "",
      },
      {
        from: "Gerhu_Sirnay",
        to: "Tsorona",
        distance: "21",
        forced_redirection: "",
      },
      {
        from: "Adwa",
        to: "Rama",
        distance: "38",
        forced_redirection: "",
      },
      {
        from: "Siero",
        to: "Inticho",
        distance: "16",
        forced_redirection: "",
      },
      {
        from: "Inticho",
        to: "Adwa",
        distance: "40",
        forced_redirection: "",
      },
      {
        from: "Adwa",
        to: "Axum",
        distance: "21",
        forced_redirection: "",
      },
      {
        from: "Axum",
        to: "Shire",
        distance: "64",
        forced_redirection: "",
      },
      {
        from: "Shire",
        to: "Sheraro",
        distance: "77",
        forced_redirection: "",
      },
      {
        from: "Shire",
        to: "Aba_Guna",
        distance: "21",
        forced_redirection: "",
      },
      {
        from: "Aba_Guna",
        to: "Mai_Aini",
        distance: "47",
        forced_redirection: "",
      },
      {
        from: "Mai_Aini",
        to: "Adi_Harush",
        distance: "11",
        forced_redirection: "",
      },
      {
        from: "Adi_Harush",
        to: "Gondar",
        distance: "207",
        forced_redirection: "",
      },
      {
        from: "Shire",
        to: "Hitsats",
        distance: "44",
        forced_redirection: "",
      },
      {
        from: "Hitsats",
        to: "Shimelba",
        distance: "50",
        forced_redirection: "",
      },
      {
        from: "Shimelba",
        to: "Denbe_Khabela",
        distance: "16",
        forced_redirection: "",
      },
      {
        from: "Sheraro",
        to: "Denbe_Khabela",
        distance: "31",
        forced_redirection: "",
      },
      {
        from: "Denbe_Khabela",
        to: "Adi_Goshu",
        distance: "66",
        forced_redirection: "",
      },
      {
        from: "Hitsats",
        to: "Dedebit",
        distance: "32",
        forced_redirection: "",
      },
      {
        from: "Dedebit",
        to: "Shimelba",
        distance: "14",
        forced_redirection: "",
      },
      {
        from: "Dedebit",
        to: "Adi_Goshu",
        distance: "87",
        forced_redirection: "",
      },
      {
        from: "Adi_Goshu",
        to: "Fireselam",
        distance: "50",
        forced_redirection: "",
      },
      {
        from: "Fireselam",
        to: "Adebay",
        distance: "23",
        forced_redirection: "",
      },
      {
        from: "Adebay",
        to: "Humera",
        distance: "19",
        forced_redirection: "",
      },
      {
        from: "Humera",
        to: "Hamdayet",
        distance: "20",
        forced_redirection: "",
      },
      {
        from: "Humera",
        to: "Adi_Ramets",
        distance: "125",
        forced_redirection: "",
      },
      {
        from: "Humera",
        to: "Dansha",
        distance: "102",
        forced_redirection: "",
      },
      {
        from: "Humera",
        to: "May_Cadera",
        distance: "30",
        forced_redirection: "",
      },
      {
        from: "May_Cadera",
        to: "Dansha",
        distance: "108",
        forced_redirection: "",
      },
      {
        from: "May_Cadera",
        to: "Adi_Ramets",
        distance: "126",
        forced_redirection: "",
      },
      {
        from: "May_Cadera",
        to: "Lugdi",
        distance: "14",
        forced_redirection: "",
      },
      {
        from: "May_Cadera",
        to: "Midre_Genet",
        distance: "47",
        forced_redirection: "",
      },
      {
        from: "Midre_Genet",
        to: "Abderafi",
        distance: "7",
        forced_redirection: "",
      },
      {
        from: "Midre_Genet",
        to: "Arema",
        distance: "108",
        forced_redirection: "",
      },
      {
        from: "Adi_Goshu",
        to: "Adi_Ramets",
        distance: "102",
        forced_redirection: "",
      },
      {
        from: "Adi_Ramets",
        to: "Gondar",
        distance: "189",
        forced_redirection: "",
      },
      {
        from: "Adi_Ramets",
        to: "Dansha",
        distance: "89",
        forced_redirection: "",
      },
      {
        from: "Dansha",
        to: "Arema",
        distance: "28",
        forced_redirection: "",
      },
      {
        from: "Arema",
        to: "Gondar",
        distance: "124",
        forced_redirection: "",
      },
      {
        from: "Gondar",
        to: "Dangur",
        distance: "61",
        forced_redirection: "",
      },
      {
        from: "Dangur",
        to: "Shehibi",
        distance: "106",
        forced_redirection: "",
      },
      {
        from: "Gondar",
        to: "Wereta",
        distance: "117",
        forced_redirection: "",
      },
      {
        from: "Wereta",
        to: "Bahir_Dar",
        distance: "61",
        forced_redirection: "",
      },
      {
        from: "Bahir_Dar",
        to: "Gilgel_Belles",
        distance: "172",
        forced_redirection: "",
      },
      {
        from: "Genete_Mariam",
        to: "Gilgel_Belles",
        distance: "70",
        forced_redirection: "",
      },
      {
        from: "Genete_Mariam",
        to: "Gubba",
        distance: "107",
        forced_redirection: "",
      },
      {
        from: "Shehibi",
        to: "Metema",
        distance: "35",
        forced_redirection: "",
      },
      {
        from: "Metema",
        to: "Midre_Genet",
        distance: "135",
        forced_redirection: "",
      },
      {
        from: "Shehibi",
        to: "Almahal",
        distance: "380",
        forced_redirection: "",
      },
      {
        from: "Almahal",
        to: "Wad_Al_Mahi",
        distance: "76",
        forced_redirection: "",
      },
      {
        from: "Almahal",
        to: "Gubba",
        distance: "51",
        forced_redirection: "",
      },
      {
        from: "Gubba",
        to: "Asosa",
        distance: "243",
        forced_redirection: "",
      },
      {
        from: "Asosa",
        to: "Bambasi",
        distance: "43",
        forced_redirection: "",
      },
      {
        from: "Bambasi",
        to: "Nedjo",
        distance: "122",
        forced_redirection: "",
      },
      {
        from: "Gilgel_Belles",
        to: "Dibate",
        distance: "77",
        forced_redirection: "",
      },
      {
        from: "Gubba",
        to: "Wembera",
        distance: "121",
        forced_redirection: "",
      },
      {
        from: "Wembera",
        to: "Bulen",
        distance: "80",
        forced_redirection: "",
      },
      {
        from: "Bulen",
        to: "Dibate",
        distance: "36",
        forced_redirection: "",
      },
      {
        from: "Bahir_Dar",
        to: "Enjebara",
        distance: "114",
        forced_redirection: "",
      },
      {
        from: "Enjebara",
        to: "Dibate",
        distance: "121",
        forced_redirection: "",
      },
      {
        from: "Enjebara",
        to: "Shambu",
        distance: "216",
        forced_redirection: "",
      },
      {
        from: "Shambu",
        to: "Bako",
        distance: "66",
        forced_redirection: "",
      },
      {
        from: "Bako",
        to: "Nedjo",
        distance: "261",
        forced_redirection: "",
      },
      {
        from: "Nedjo",
        to: "Dambidollo",
        distance: "198",
        forced_redirection: "",
      },
      {
        from: "Dambidollo",
        to: "Bambasi",
        distance: "224",
        forced_redirection: "",
      },
      {
        from: "Bako",
        to: "Ambo",
        distance: "121",
        forced_redirection: "",
      },
      {
        from: "Ambo",
        to: "Gimbi",
        distance: "29",
        forced_redirection: "",
      },
      {
        from: "Ambo",
        to: "Addis_Ababa",
        distance: "115",
        forced_redirection: "",
      },
      {
        from: "Bahir_Dar",
        to: "Addis_Ababa",
        distance: "486",
        forced_redirection: "",
      },
      {
        from: "Addis_Ababa",
        to: "Mojo",
        distance: "77",
        forced_redirection: "",
      },
      {
        from: "Mojo",
        to: "Nazret",
        distance: "20",
        forced_redirection: "",
      },
      {
        from: "Nazret",
        to: "Awash",
        distance: "123",
        forced_redirection: "",
      },
      {
        from: "Awash",
        to: "Mieso",
        distance: "79",
        forced_redirection: "",
      },
      {
        from: "Awash",
        to: "Galafi",
        distance: "488",
        forced_redirection: "",
      },
      {
        from: "Mojo",
        to: "Shashamane",
        distance: "178",
        forced_redirection: "",
      },
      {
        from: "Shashamane",
        to: "Dilla",
        distance: "110",
        forced_redirection: "",
      },
      {
        from: "Dilla",
        to: "Negele",
        distance: "260",
        forced_redirection: "",
      },
    ],
  },
];
